### ISSUE TITLE
随机的逻辑可否调整一下

### ISSUE THREAD

**Issue by Dboy233** [ideshun/bing-wallpaper#1]
我发现随机的时候很大概率随机到同样的图片，
可否在请求中让请求方添加一个请求头来标记唯一请求，每次减少重复图片。我用大哥的api搞了个快捷指令。这样每天我都换个壁纸😁![image](https://github.com/ideshun/bing-wallpaper/assets/37604230/a2b6a9b5-d4e3-4775-9204-a86ca4db1713)

**Comment by ideshun** [comment]
随机代码逻辑应该没问题，必应提供的接口只能取到取16天内的壁纸。
增加了一个idx参数，指定取第几天前的壁纸，试一下吧。
https://bz.w3h5.com/img/uhd 是当天的超清壁纸。
https://bz.w3h5.com/img/uhd?idx=1 就是一天前（昨天）的。

**Comment by Dboy233** [comment]
好的
